export const students = [
  {
    id: "101",
    name: "john_doe",
    email: "john.doe@example.com",
    password: "Password123",
    fatherName: "Robert Doe",
    motherName: "Linda Doe",
    class: "11",
    section: "A",
    dob: "2008-04-12",
    gender: "Male",
    bloodGroup: "O+",
    address: "123 Main St, Springfield",
    phone: "9876543210",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: "102",
    name: "jane_smith",
    email: "jane.smith@example.com",
    password: "Jane@2024",
    fatherName: "Thomas Smith",
    motherName: "Emily Smith",
    class: "11",
    section: "B",
    dob: "2009-07-23",
    gender: "Female",
    bloodGroup: "A+",
    address: "456 Oak St, Shelbyville",
    phone: "9876501234",
    profileImage: "",
  },
  {
    id: "103",
    name: "mike_jordan",
    email: "mike.jordan@example.com",
    password: "MikePass789",
    fatherName: "Michael Jordan",
    motherName: "Sarah Jordan",
    class: "11",
    section: "C",
    dob: "2010-03-15",
    gender: "Male",
    bloodGroup: "B+",
    address: "789 Pine St, Ogdenville",
    phone: "9812345678",
    profileImage: "",
  },
  {
    id: "104",
    name: "ryan_clark",
    email: "ryan.clark@example.com",
    password: "Clark2024!",
    fatherName: "David Clark",
    motherName: "Helen Clark",
    class: "12",
    section: "B",
    dob: "2012-11-11",
    gender: "Male",
    bloodGroup: "O-",
    address: "654 Maple St, Brockway",
    phone: "9823456789",
    profileImage: "",
  },
  {
    id: "105",
    name: "olivia_lee",
    email: "olivia.lee@example.com",
    password: "OliviaLee$$",
    fatherName: "Kevin Lee",
    motherName: "Grace Lee",
    class: "12",
    section: "C",
    dob: "2013-08-21",
    gender: "Female",
    bloodGroup: "A-",
    address: "987 Cedar St, Capital City",
    phone: "9801234567",
    profileImage: "",
  },
  {
    id: "106",
    name: "sophia_martin",
    email: "sophia.martin@example.com",
    password: "SophiaM#1",
    fatherName: "Henry Martin",
    motherName: "Isabella Martin",
    class: "11",
    section: "B",
    dob: "2009-09-05",
    gender: "Female",
    bloodGroup: "AB-",
    address: "753 Walnut St, Shelbyville",
    phone: "9856783210",
    profileImage: "",
  },
  {
    id: "107",
    name: "ava_turner",
    email: "ava.turner@example.com",
    password: "AvaT@123",
    fatherName: "Joseph Turner",
    motherName: "Emma Turner",
    class: "12",
    section: "B",
    dob: "2011-06-29",
    gender: "Female",
    bloodGroup: "A+",
    address: "890 Aspen St, North Haverbrook",
    phone: "9877891234",
    profileImage: "",
  },
  {
    id: "108",
    name: "emma_brown",
    email: "emma.brown@example.com",
    password: "Emma123@#",
    fatherName: "Daniel Brown",
    motherName: "Laura Brown",
    class: "12",
    section: "A",
    dob: "2011-05-30",
    gender: "Female",
    bloodGroup: "AB+",
    address: "321 Elm St, North Haverbrook",
    phone: "9845671230",
    profileImage: "",
  },
  {
    id: "109",
    name: "noah_wilson",
    email: "noah.wilson@example.com",
    password: "Noah@2025",
    fatherName: "George Wilson",
    motherName: "Anna Wilson",
    class: "11",
    section: "A",
    dob: "2008-12-10",
    gender: "Male",
    bloodGroup: "B-",
    address: "159 Birch St, Springfield",
    phone: "9812340987",
    profileImage: "",
  },
  {
    id: "110",
    name: "liam_scott",
    email: "liam.scott@example.com",
    password: "LiamS321!",
    fatherName: "Andrew Scott",
    motherName: "Natalie Scott",
    class: "12",
    section: "A",
    dob: "2010-02-17",
    gender: "Male",
    bloodGroup: "O+",
    address: "456 Willow St, Ogdenville",
    phone: "9834567890",
    profileImage: "",
  },
  {
    id: "111",
    name: "liam_wilson",
    email: "liam.wilson@example.com",
    password: "LiamW#2",
    fatherName: "James Wilson",
    motherName: "Karen Wilson",
    class: "11",
    section: "B",
    dob: "2009-04-15",
    gender: "Male",
    bloodGroup: "A+",
    address: "801 Maple Ave, Springfield",
    phone: "9856732101",
    profileImage: "",
  },
  {
    id: "112",
    name: "emma_jones",
    email: "emma.jones@example.com",
    password: "EmmaJ#3",
    fatherName: "Andrew Jones",
    motherName: "Diana Jones",
    class: "11",
    section: "B",
    dob: "2009-12-22",
    gender: "Female",
    bloodGroup: "B-",
    address: "410 Oak St, Shelbyville",
    phone: "9845632178",
    profileImage: "",
  },
  {
    id: "113",
    name: "noah_smith",
    email: "noah.smith@example.com",
    password: "NoahS#4",
    fatherName: "Robert Smith",
    motherName: "Emily Smith",
    class: "11",
    section: "B",
    dob: "2009-02-28",
    gender: "Male",
    bloodGroup: "O+",
    address: "332 Birch Rd, Ogdenville",
    phone: "9867123456",
    profileImage: "",
  },
  {
    id: "114",
    name: "ava_brown",
    email: "ava.brown@example.com",
    password: "AvaB#5",
    fatherName: "Daniel Brown",
    motherName: "Laura Brown",
    class: "11",
    section: "B",
    dob: "2009-07-09",
    gender: "Female",
    bloodGroup: "AB+",
    address: "650 Pine Ln, North Haverbrook",
    phone: "9834567890",
    profileImage: "",
  },
  {
    id: "115",
    name: "ethan_davis",
    email: "ethan.davis@example.com",
    password: "EthanD#6",
    fatherName: "Steven Davis",
    motherName: "Michelle Davis",
    class: "11",
    section: "B",
    dob: "2009-10-11",
    gender: "Male",
    bloodGroup: "B+",
    address: "123 Elm St, Springfield",
    phone: "9823456781",
    profileImage: "",
  },
  {
    id: "116",
    name: "isabella_moore",
    email: "isabella.moore@example.com",
    password: "IsabellaM#7",
    fatherName: "Philip Moore",
    motherName: "Anna Moore",
    class: "11",
    section: "B",
    dob: "2009-05-23",
    gender: "Female",
    bloodGroup: "O-",
    address: "452 Aspen Dr, Ogdenville",
    phone: "9812345698",
    profileImage: "",
  },
  {
    id: "117",
    name: "james_taylor",
    email: "james.taylor@example.com",
    password: "JamesT#8",
    fatherName: "Brian Taylor",
    motherName: "Rebecca Taylor",
    class: "11",
    section: "B",
    dob: "2009-06-14",
    gender: "Male",
    bloodGroup: "A-",
    address: "88 Hickory Ct, Shelbyville",
    phone: "9801234567",
    profileImage: "",
  },
  {
    id: "118",
    name: "mia_clark",
    email: "mia.clark@example.com",
    password: "MiaC#9",
    fatherName: "Kevin Clark",
    motherName: "Sophia Clark",
    class: "11",
    section: "B",
    dob: "2009-03-19",
    gender: "Female",
    bloodGroup: "B+",
    address: "321 Willow Blvd, Capital City",
    phone: "9876541230",
    profileImage: "",
  },
  {
    id: "119",
    name: "logan_miller",
    email: "logan.miller@example.com",
    password: "LoganM#10",
    fatherName: "Mark Miller",
    motherName: "Linda Miller",
    class: "11",
    section: "B",
    dob: "2009-01-30",
    gender: "Male",
    bloodGroup: "AB-",
    address: "789 Cedar St, North Haverbrook",
    phone: "9841203987",
    profileImage: "",
  },
  {
    id: "120",
    name: "charlotte_hall",
    email: "charlotte.hall@example.com",
    password: "CharlotteH#11",
    fatherName: "Samuel Hall",
    motherName: "Megan Hall",
    class: "11",
    section: "B",
    dob: "2009-08-17",
    gender: "Female",
    bloodGroup: "A+",
    address: "456 Fir Dr, Springfield",
    phone: "9820314567",
    profileImage: "",
  },
  {
    id: "121",
    name: "lucas_white",
    email: "lucas.white@example.com",
    password: "LucasW#12",
    fatherName: "Joseph White",
    motherName: "Patricia White",
    class: "11",
    section: "B",
    dob: "2009-11-08",
    gender: "Male",
    bloodGroup: "O+",
    address: "901 Juniper Way, Ogdenville",
    phone: "9856237890",
    profileImage: "",
  },
  {
    id: "122",
    name: "amelia_walker",
    email: "amelia.walker@example.com",
    password: "AmeliaW#13",
    fatherName: "Anthony Walker",
    motherName: "Rachel Walker",
    class: "11",
    section: "B",
    dob: "2009-09-02",
    gender: "Female",
    bloodGroup: "B-",
    address: "600 Poplar Ln, Shelbyville",
    phone: "9832104567",
    profileImage: "",
  },
  {
    id: "123",
    name: "jack_harris",
    email: "jack.harris@example.com",
    password: "JackH#14",
    fatherName: "George Harris",
    motherName: "Deborah Harris",
    class: "11",
    section: "B",
    dob: "2009-07-27",
    gender: "Male",
    bloodGroup: "A+",
    address: "300 Magnolia Blvd, Springfield",
    phone: "9823456791",
    profileImage: "",
  },
  {
    id: "124",
    name: "harper_thomas",
    email: "harper.thomas@example.com",
    password: "HarperT#15",
    fatherName: "Thomas Thomas",
    motherName: "Catherine Thomas",
    class: "11",
    section: "B",
    dob: "2009-05-06",
    gender: "Female",
    bloodGroup: "O-",
    address: "734 Cypress Rd, Capital City",
    phone: "9812340976",
    profileImage: "",
  },
  {
    id: "125",
    name: "benjamin_scott",
    email: "benjamin.scott@example.com",
    password: "BenjaminS#16",
    fatherName: "Eric Scott",
    motherName: "Barbara Scott",
    class: "11",
    section: "B",
    dob: "2009-04-25",
    gender: "Male",
    bloodGroup: "AB+",
    address: "850 Redwood St, Ogdenville",
    phone: "9809876543",
    profileImage: "",
  },
  {
    id: "126",
    name: "evelyn_martinez",
    email: "evelyn.martinez@example.com",
    password: "EvelynM#17",
    fatherName: "Carlos Martinez",
    motherName: "Lucia Martinez",
    class: "11",
    section: "B",
    dob: "2009-06-01",
    gender: "Female",
    bloodGroup: "B+",
    address: "612 Chestnut Dr, Shelbyville",
    phone: "9873214567",
    profileImage: "",
  },
  {
    id: "127",
    name: "henry_lewis",
    email: "henry.lewis@example.com",
    password: "HenryL#18",
    fatherName: "Aaron Lewis",
    motherName: "Paula Lewis",
    class: "11",
    section: "B",
    dob: "2009-10-04",
    gender: "Male",
    bloodGroup: "A-",
    address: "909 Sequoia Ln, Springfield",
    phone: "9845623478",
    profileImage: "",
  },
  {
    id: "128",
    name: "abigail_young",
    email: "abigail.young@example.com",
    password: "AbigailY#19",
    fatherName: "Kyle Young",
    motherName: "Melissa Young",
    class: "11",
    section: "B",
    dob: "2009-03-11",
    gender: "Female",
    bloodGroup: "O+",
    address: "745 Spruce Ave, North Haverbrook",
    phone: "9851203984",
    profileImage: "",
  },
  {
    id: "129",
    name: "william_king",
    email: "william.king@example.com",
    password: "WilliamK#20",
    fatherName: "Edward King",
    motherName: "Janet King",
    class: "11",
    section: "B",
    dob: "2009-12-10",
    gender: "Male",
    bloodGroup: "B-",
    address: "120 Sycamore St, Capital City",
    phone: "9823412908",
    profileImage: "",
  },
  {
    id: "130",
    name: "ella_lee",
    email: "ella.lee@example.com",
    password: "EllaL#21",
    fatherName: "Peter Lee",
    motherName: "Grace Lee",
    class: "11",
    section: "B",
    dob: "2009-08-05",
    gender: "Female",
    bloodGroup: "AB-",
    address: "204 Beechwood Ln, Ogdenville",
    phone: "9801203948",
    profileImage: "",
  },
];

export const teachers = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    password: "Alice@123",
    qualification: "M.Sc. Mathematics",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-123-4567",
    gender: "Female",
    bloodGroup: "O+",
    dob: "1985-03-15",
    address: "123 Maple Street, Springfield",
    about: "Passionate about numbers and problem-solving.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 2,
    name: "Brian Smith",
    email: "brian.smith@example.com",
    password: "Brian@123",
    qualification: "Ph.D. Physics",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-234-5678",
    gender: "Male",
    bloodGroup: "A+",
    dob: "1979-11-22",
    address: "456 Oak Avenue, Greenville",
    about: "Loves teaching science and conducting experiments.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 3,
    name: "Cynthia Lee",
    email: "cynthia.lee@example.com",
    password: "Cynthia@123",
    qualification: "B.Ed. Physical Education",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-345-6789",
    gender: "Female",
    bloodGroup: "B+",
    dob: "1990-06-10",
    address: "789 Pine Road, Riverdale",
    about: "Dedicated to promoting physical wellness in students.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 4,
    name: "David Miller",
    email: "david.miller@example.com",
    password: "David@123",
    qualification: "M.Sc. Chemistry",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-456-7890",
    gender: "Male",
    bloodGroup: "AB+",
    dob: "1982-02-28",
    address: "101 Birch Lane, Hilltown",
    about: "Enjoys engaging students with real-world science applications.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 5,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    password: "Emily@123",
    qualification: "M.A. Mathematics",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-567-8901",
    gender: "Female",
    bloodGroup: "O-",
    dob: "1988-07-19",
    address: "202 Cedar Street, Brookfield",
    about: "Strives to make math enjoyable for everyone.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 6,
    name: "Frank Thompson",
    email: "frank.thompson@example.com",
    password: "Frank@123",
    qualification: "M.P.Ed.",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-678-9012",
    gender: "Male",
    bloodGroup: "A-",
    dob: "1980-12-05",
    address: "303 Spruce Blvd, Lakeside",
    about: "A former athlete turned educator.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 7,
    name: "Grace Wilson",
    email: "grace.wilson@example.com",
    password: "Grace@123",
    qualification: "M.Sc. Biology",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-789-0123",
    gender: "Female",
    bloodGroup: "B-",
    dob: "1992-09-30",
    address: "404 Elm Drive, Meadowville",
    about: "Biology teacher with a passion for nature.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 8,
    name: "Henry Adams",
    email: "henry.adams@example.com",
    password: "Henry@123",
    qualification: "M.Sc. Mathematics",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-890-1234",
    gender: "Male",
    bloodGroup: "AB-",
    dob: "1987-04-17",
    address: "505 Willow Road, Forest Glen",
    about: "Enjoys teaching advanced calculus and statistics.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 9,
    name: "Isabella Clark",
    email: "isabella.clark@example.com",
    password: "Isabella@123",
    qualification: "M.A. Sports Science",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-901-2345",
    gender: "Female",
    bloodGroup: "O+",
    dob: "1991-01-26",
    address: "606 Aspen Street, Bayview",
    about: "Focuses on developing young athletes.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
  {
    id: 10,
    name: "Jack Turner",
    email: "jack.turner@example.com",
    password: "Jack@123",
    qualification: "M.Ed. Science Education",
    department: ["Mathematics", "Science", "Sport"],
    phone: "+1-555-012-3456",
    gender: "Male",
    bloodGroup: "A+",
    dob: "1983-08-12",
    address: "707 Poplar Avenue, Clearview",
    about: "Believes in hands-on learning experiences.",
    profileImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNL_ZnOTpXSvhf1UaK7beHey2BX42U6solRA&s",
  },
];
